name: my-xmonad
version: 0.1.0.0
author: "flyingsl0ths"

build-type: Simple

dependencies:
  - base >= 4.7 && < 5
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17
  - containers

library:
  source-dirs: src

executables:
  my-xmonad:
    main: xmonad.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -O3
    dependencies:
      - my-xmonad
