Diagnostics:
  ClangTidy:
    Add: modernize*
    Remove: modernize-use-trailing-return-type
    CheckOptions:
      readability-identifier-naming.VariableCase: lower_case
      readability-identifier-naming.ClassMemberPrefix: m_

---
If:
  PathMatch: *\.*pp
  Add: [-std=c++17, -Wall, -Werror, -Wextra, -Wsign-conversion]

---
If:
  PathMatch: *\.{c,h}
  Add: [-std=c99, -Wall, -Werror, -Wextra, -Wsign-conversion, -pedantic]