vim.o.encoding = "UTF-8"
vim.o.background = "dark"
vim.o.guifont = "JetBrainsMonoMedium Nerd Font 11"
vim.o.scrolljump = 5
vim.bo.synmaxcol = 140
vim.o.cmdheight = 2
vim.bo.tabstop = 4
vim.bo.shiftwidth = 4
vim.bo.softtabstop = 4
vim.o.mouse = "a"
vim.o.modelines = 4
vim.o.history = 20
vim.o.backspace = "indent,eol,start"
vim.o.errorbells = false
vim.o.wildignore =
    "wildignore+ = */tmp/*,*.so,*.swp,*.zip,*/vendor/*,*/\\.git/*"
vim.o.autoread = true
vim.o.smarttab = true
vim.bo.expandtab = true
vim.o.modeline = true
vim.o.magic = true
vim.o.gdefault = true
vim.o.number = true
vim.o.relativenumber = true
vim.wo.cursorline = false
vim.o.startofline = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.title = true
vim.o.ruler = true
vim.o.incsearch = true
vim.o.backup = false
vim.o.wildmenu = true
vim.bo.autoindent = true
vim.bo.smartindent = true
vim.wo.wrap = true
vim.o.showmode = false
vim.o.hidden = true
vim.updatetime = 300
vim.o.shortmess = "c"
vim.cmd "set tags=tags;~"
vim.o.lazyredraw = false
vim.o.termguicolors = true
vim.o.spelllang = "en_us"
vim.cmd "set clipboard+=unnamedplus"
vim.cmd "set path+=**"
vim.cmd "set noswapfile"
vim.g.python3_host_prog ="/usr/bin/python3"
vim.g.PreserveNoEOL = true
vim.g.markdown_fenced_languages = {
  "ts=typescript"
}
