[[language]]
name = "python"
language-servers = [ "basedpyright" , "ruff"]
formatter = { command = "ruff", args = ["format", "--line-length", "80", "-"] }
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "html"
formatter = { command = 'biome', args = ["format"] }

[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

[[language]]
name = "json"
formatter = { command = 'biome', args = ["format"] }

[[language]]
name = "css"
formatter = { command = 'biome', args = ["format"] }

[[language]]
name = "javascript"
formatter = { command = 'biome', args = ["format"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'biome', args = ["format"] }
auto-format = true

[[language]]
name = "haskell"
formatter = { command = "stylish-haskell", args = [] }
auto-format = true

[[language]]
name = "purescript"
formatter = { command = 'purs-tidy', args = ["format"] }
auto-format = true

[[language]]
name = "swift"
formatter = { command = 'swift-format', args = ["format"] }
auto-format = true
